### ISSUE TITLE
Separate context creation

### ISSUE THREAD

**Issue by konalegi** [DmitryTsepelev/ar_lazy_preload#46] opened 2020-12-14 17:49 UTC
Thanks for your gem and your work! 👍 

**Introduction**

Firstly to properly describe our problem, I want to show our use cases and where it comes from. 
Since we extensively started using this gem, we faced the issue when we need to create a context for a particular set of objects which was not loaded by relation. For instance, some smart service returns as 10 objects, which were loaded by code which we cannot control. I've come up with the following solution:
```
def register(objects)
  objects = Array.wrap(objects)

  context = ArLazyPreload::Context.register(
    records: Array.wrap(objects),
    association_tree: [],
    auto_preload: true
  )

  # This always rewrites the context to have predictable behaviour
  objects.each { |object| object.lazy_preload_context = context }

  context
end
```
It works pretty well for now and solves most of our problems.

**Problem**

Imagine we have something similar, but we need to tie up a different sets of objects into the same context. 
for instance, we have the following GQL query 
```
users {
  skills {
    jobs { id }
  }
}
```
and `skills` is not an association with users, but generated by some smart ML service. But I want able to register those skills into the same context to make preload work properly
```
find_skills_for_user - returns array of skills
users = User.all.preload_associations_lazily
skills = users.flat_map{|user| find_skills_for_user(user) }
skills.each{|skill| skill.jobs } - this is going to generate N+1, because they are not bounded to 
the same context. I could use function defined above, but it's going to have less queries, but still it's N+1
```

I hope I could explain the problem.
I really appreciate if you could guide/help how I could solve this. Thanks in advance.

**Comment by konalegi** [comment] 2020-12-14 18:00
Probably it's better to make PR with failing spec to see the clear example.

**Comment by DmitryTsepelev** [comment] 2020-12-15 08:30
Hi @konalegi! The problem is that the gem is tied with AR associations—all the hooks happen when _associations_ are [loaded](https://github.com/DmitryTsepelev/ar_lazy_preload/blob/master/lib/ar_lazy_preload/active_record/association.rb#L7). I wonder if can somehow _mimic_ the association behavior for `skills`: if AR thought that `User#skills` is (already loaded) association, the gem would take care for the rest (I might be wrong about the process of loading skills, just an idea):

```ruby
class User
  has_many :skills # not sure it will work, we need to have it as "association" to make gem work
end

def fulfill_skills_for_user(users)
  skills_by_user = {} # we need to have a hash of <user_id, skill_id> from somewhere
  users.each { |user| user.skills = skills_by_user[user.id] } # and maybe do something with association state
  skills.values.uniq
end

users = User.all.preload_associations_lazily
skills = fulfill_skills_for_user(users)
```

**Comment by konalegi** [comment] 2020-12-21 16:46
@DmitryTsepelev thanks for your answer, unfortunately, it doesn't work for us. I couldn't make it as an association. I think this could be solved by using a tree of "association", but since it's not an association, then probably out of the scope of this gem.

**Comment by DmitryTsepelev** [comment] 2020-12-22 16:45
Yeah, I feel like we cannot do that using the current approach 😞I'll close the issue for now

**Closed by DmitryTsepelev** 2020-12-22 16:45 UTC
